# -*- coding: utf-8 -*-
"""gues the numbe Gamer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KlwWZvxfkJpk4r02Y2jJoilRuEtliGZJ
"""

total_tries = int(input("Enter the total tries: "))
find = 8
tried = 0

for i in range(total_tries):
    guess = int(input("Guess the number: "))
    tried += 1
    print("Tried:", tried)

    if guess == find:
        print(" You found it!")
        break
    elif guess > find:
        print("Too high!")
    else:
        print("Too low!")


    print("You have", total_tries - tried, "tries left.\n")

print("====================================")

if tried < total_tries and guess == find:
    print(" You win the game!")
else:
    print("===================")
    print(f"Your tries are completed: {total_tries}")
    print("===================")
    print()
    print("  Game Over  ")

